### Jointure des données: Prix transactionnel DGI + POIs géomarketing + données HCP

In [ ]:
import os 
os.chdir('C:/Users/del/Desktop/prix-immobilier-evaluation')

In [ ]:
import pandas as pd
# prix DGI
df1 = pd.read_excel("geomarketing\\Referentiel_Prix_Casablanca_ENRICHI.xlsx", sheet_name="Référentiel Prix Casablanca", header=3)
# POIs 
df2 = pd.read_excel("geomarketing\\Referentiel_Prix_Casablanca_ENRICHI.xlsx", sheet_name="Métriques par zone")

In [61]:
df1.head()

,Préfecture,Arrondissement,Code Zone,Zone déchiffrée,Type de bien,État,Condition / Zonage,Prix Terrain au m² (DH),Prix Construction au m² (DH)
0,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Ancien,NaN,11000.0,NaN
1,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Récent,NaN,14000.0,NaN
2,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Neuf,NaN,16000.0,NaN
3,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Terrain ZI,Loti,< à R+10,32000.0,NaN
4,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Terrain ZI,Loti,>= à R+10,41000.0,NaN

In [63]:
cols_poi = df2.columns
cols_poi

Index(['CodeZone', 'Préfecture', 'Arrondissement', 'Zone déchiffrée', 'lat',
       'lon', 'geocode_quality', 'nb_education_500m', 'nb_education_1000m',
       'dist_education_min_m', 'nb_banque_500m', 'nb_banque_1000m',
       'dist_banque_min_m', 'nb_sante_500m', 'nb_sante_1000m',
       'dist_sante_min_m', 'nb_commerce_500m', 'nb_commerce_1000m',
       'dist_commerce_min_m', 'nb_transport_500m', 'nb_transport_1000m',
       'dist_transport_min_m', 'nb_environnement_500m',
       'nb_environnement_1000m', 'dist_environnement_min_m',
       'nb_nuisance_500m', 'nb_nuisance_1000m', 'dist_nuisance_min_m',
       'dist_autoroute_min_m', 'dist_voie_primaire_min_m',
       'dist_voie_secondaire_min_m', 'score_amenites_500m',
       'score_amenites_1km', 'score_nuisance_500m', 'score_accessibilite',
       'dist_boulevard_principal', 'nb_axes_500m', 'centralite_routiere',
       'dist_tram', 'nb_stations_1km', 'temps_transport_centre', 'temps_CFC',
       'temps_Maarif', 'temps_SidiMaarouf', 'temps_port', 'nb_ecoles_1km',
       'dist_ecole', 'densite_education', 'nb_sante_1km', 'dist_clinique',
       'nb_restaurants_500m', 'nb_commerces_1km', 'nb_banques_1km',
       'nb_GAB_1km', 'dist_mer', 'dist_parc', 'surface_verte_1km',
       'nb_nuisance'],
      dtype='str')

In [64]:
cols_poi = cols_poi.drop(['CodeZone', 'Préfecture', 'Arrondissement','lat','lon', 'geocode_quality', 'nb_education_500m', 'nb_banque_500m', 'nb_sante_500m','nb_commerce_500m','nb_transport_500m','nb_environnement_500m','nb_environnement_1000m','nb_education_1000m', 'nb_sante_1000m', 'nb_commerce_1000m', 'nb_banque_1000m', 'nb_transport_1000m', 'nb_environnement_1000m', 'nb_nuisance_1000m', 'score_amenites_500m',  'score_amenites_1km', 'nb_GAB_1km','score_nuisance_500m', 'score_accessibilite',  'centralite_routiere',])

In [65]:
df2 = df2[cols_poi]
df2.head()

,Zone déchiffrée,dist_education_min_m,dist_banque_min_m,dist_sante_min_m,dist_commerce_min_m,dist_transport_min_m,dist_environnement_min_m,nb_nuisance_500m,dist_nuisance_min_m,dist_autoroute_min_m,...,densite_education,nb_sante_1km,dist_clinique,nb_restaurants_500m,nb_commerces_1km,nb_banques_1km,dist_mer,dist_parc,surface_verte_1km,nb_nuisance
0,Av. des FAR,112.0,8.0,457.0,26.0,30.0,148.0,2.0,204.0,231.0,...,2.23,8.0,457.0,12.0,18.0,8.0,292.0,381.0,82703.0,9.0
1,Av. Hassan II,347.0,129.0,54.0,65.0,55.0,117.0,1.0,472.0,1490.0,...,5.09,80.0,213.0,50.0,53.0,91.0,1654.0,117.0,366630.0,7.0
2,Av. Pasteur,461.0,284.0,294.0,269.0,251.0,389.0,8.0,77.0,839.0,...,0.64,9.0,830.0,13.0,8.0,24.0,691.0,413.0,74950.0,20.0
3,Bd Ambassadeur Ben Aicha,112.0,8.0,457.0,26.0,30.0,148.0,2.0,204.0,231.0,...,2.23,8.0,457.0,12.0,18.0,8.0,292.0,381.0,82703.0,9.0
4,Bd Anfa (de Bd Zerktouni à Place Oued El Makha...,112.0,8.0,457.0,26.0,30.0,148.0,2.0,204.0,231.0,...,2.23,8.0,457.0,12.0,18.0,8.0,292.0,381.0,82703.0,9.0

In [66]:
df = df1.merge(df2, on="Zone déchiffrée", how="left")

In [67]:
df.head()

,Préfecture,Arrondissement,Code Zone,Zone déchiffrée,Type de bien,État,Condition / Zonage,Prix Terrain au m² (DH),Prix Construction au m² (DH),dist_education_min_m,...,densite_education,nb_sante_1km,dist_clinique,nb_restaurants_500m,nb_commerces_1km,nb_banques_1km,dist_mer,dist_parc,surface_verte_1km,nb_nuisance
0,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Ancien,NaN,11000.0,NaN,112.0,...,2.23,8.0,457.0,12.0,18.0,8.0,292.0,381.0,82703.0,9.0
1,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Récent,NaN,14000.0,NaN,112.0,...,2.23,8.0,457.0,12.0,18.0,8.0,292.0,381.0,82703.0,9.0
2,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Neuf,NaN,16000.0,NaN,112.0,...,2.23,8.0,457.0,12.0,18.0,8.0,292.0,381.0,82703.0,9.0
3,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Terrain ZI,Loti,< à R+10,32000.0,NaN,112.0,...,2.23,8.0,457.0,12.0,18.0,8.0,292.0,381.0,82703.0,9.0
4,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Terrain ZI,Loti,>= à R+10,41000.0,NaN,112.0,...,2.23,8.0,457.0,12.0,18.0,8.0,292.0,381.0,82703.0,9.0

In [68]:
df = df.drop(columns=['Prix Construction au m² (DH)'])

In [69]:
df = df.dropna(subset=['Prix Terrain au m² (DH)','dist_banque_min_m'])

In [70]:
df.isna().sum()

Préfecture                       0
Arrondissement                   0
Code Zone                        0
Zone déchiffrée                  0
Type de bien                     0
État                             0
Condition / Zonage            1176
Prix Terrain au m² (DH)          0
dist_education_min_m             0
dist_banque_min_m                0
dist_sante_min_m                 0
dist_commerce_min_m              0
dist_transport_min_m             0
dist_environnement_min_m         0
nb_nuisance_500m                 0
dist_nuisance_min_m              0
dist_autoroute_min_m             0
dist_voie_primaire_min_m         0
dist_voie_secondaire_min_m       0
dist_boulevard_principal         0
nb_axes_500m                     0
dist_tram                        0
nb_stations_1km                  0
temps_transport_centre           0
temps_CFC                        0
temps_Maarif                     0
temps_SidiMaarouf                0
temps_port                       0
nb_ecoles_1km                    0
dist_ecole                       0
densite_education                0
nb_sante_1km                     0
dist_clinique                    0
nb_restaurants_500m              0
nb_commerces_1km                 0
nb_banques_1km                   0
dist_mer                         0
dist_parc                        0
surface_verte_1km                0
nb_nuisance                      0
dtype: int64

In [71]:
# données HCP
df3 = pd.read_csv("scrapping\\data\\data_hcp.csv")
df3.head()

,commune,Densite_pop_km2,Part_population_15_59_ans,Taille_de_ménage,Taux_activité,Taux_chômage,Part_salariés_parmi_actifs,Taux_analphabétisme,Part_population_niveau_études_supérieur,Taux_croissance
0,Anfa,3995,58.7,3.0,47.1,14.3,69.7,8.2,33.5,-29.9
1,Maârif,11257,61.0,2.7,50.1,10.9,72.1,6.4,39.8,-18.2
2,Sidi Belyout,13791,61.2,2.9,47.6,19.5,70.1,10.6,21.3,-27.1
3,Ben M'Sick,33886,61.0,3.6,42.2,24.6,62.9,15.8,11.6,-19.9
4,Sbata,22209,61.4,3.8,42.7,22.2,23.7,13.1,15.3,-12.6

In [72]:
df3.rename(columns={"commune": "Arrondissement"}, inplace=True)

In [73]:
df = df.merge(df3, on="Arrondissement", how="left")
df.head()

,Préfecture,Arrondissement,Code Zone,Zone déchiffrée,Type de bien,État,Condition / Zonage,Prix Terrain au m² (DH),dist_education_min_m,dist_banque_min_m,...,nb_nuisance,Densite_pop_km2,Part_population_15_59_ans,Taille_de_ménage,Taux_activité,Taux_chômage,Part_salariés_parmi_actifs,Taux_analphabétisme,Part_population_niveau_études_supérieur,Taux_croissance
0,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Ancien,NaN,11000.0,112.0,8.0,...,9.0,13791,61.2,2.9,47.6,19.5,70.1,10.6,21.3,-27.1
1,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Récent,NaN,14000.0,112.0,8.0,...,9.0,13791,61.2,2.9,47.6,19.5,70.1,10.6,21.3,-27.1
2,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Appartement,Neuf,NaN,16000.0,112.0,8.0,...,9.0,13791,61.2,2.9,47.6,19.5,70.1,10.6,21.3,-27.1
3,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Terrain ZI,Loti,< à R+10,32000.0,112.0,8.0,...,9.0,13791,61.2,2.9,47.6,19.5,70.1,10.6,21.3,-27.1
4,Casa-Anfa,Sidi Belyout,CC-SB1,Av. des FAR,Terrain ZI,Loti,>= à R+10,41000.0,112.0,8.0,...,9.0,13791,61.2,2.9,47.6,19.5,70.1,10.6,21.3,-27.1

In [74]:
df.to_csv("scrapping\\data\\data_finale.csv", index=False)